Feat/37153 node relation
DP6/pipeline-penguin pull request #38
Opened 2022-05-03 20:18 UTC by flaviovitorino

2022-05-06 20:47 UTC, jubelcassio commented on pipeline_penguin/core/node_relation/node_relation.py
> +        self.source = source
Só vou pedir pra deixar os atributos como "protected": 
self.__source
self.__destination

2022-05-06 20:48 UTC, jubelcassio commented on use_pp.py
> +from pipeline_penguin import PipelinePenguin
Haha, acho que esse arquivo precisa ser excluído

2022-05-06 20:55 UTC, jubelcassio commented on pipeline_penguin/core/data_node/data_node.py
> +    def add_relation(self,relation: "NodeRelation",isDestination:bool) -> None:
Não compreendi o propósito da flag de "isDestination". Ela deveria ser para validar se o NodeRelation já possui o DataNode?

2022-05-06 20:57 UTC, jubelcassio requested changes
@flaviovitorino Em geral está bom, porém pedi alguns ajustes simples ao código. Também seria bom adicionar alguns testes unitários para a nova classe. 

Se tiver alguma dúvida, pode me procurar!

2022-05-12 13:38 UTC, flaviovitorino commented on pipeline_penguin/core/data_node/data_node.py
> +    def add_relation(self,relation: "NodeRelation",isDestination:bool) -> None:
Na verdade eu pensei na flag pra informar, na hora de adicionar a relatiion se o DataNote é um source ou um destination.

2022-06-09 16:51 UTC, merged